DECLARE
v_exists NUMBER;
BEGIN
  -- Check if the column NUMBER_OF_CHECKPOINTS exists
SELECT COUNT(*)
INTO v_exists
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'MATCHES'
  AND COLUMN_NAME = 'NUMBER_OF_CHECKPOINTS';

IF v_exists > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE MATCHES DROP COLUMN NUMBER_OF_CHECKPOINTS';
END IF;

  -- Check if the column NUMBER_OF_CHECKPOINTS_LEFT exists
SELECT COUNT(*)
INTO v_exists
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'MATCHES'
  AND COLUMN_NAME = 'NUMBER_OF_CHECKPOINTS_LEFT';

IF v_exists > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE MATCHES DROP COLUMN NUMBER_OF_CHECKPOINTS_LEFT';
END IF;
END;