spring:
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@//192.168.1.125:1521/LACONIC}
    username: ${DB_USERNAME:jobonic}
    password: ${DB_PASSWORD:jobonic}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA46B53gbtOwxNSSyBjGTXfuWovjckNEwkhaoVDJYp3Jsy3RfY7ftJybx9aTOMh+9+AWgQy9sfE5L6wdSnAxsimCJg6/F2rMR2xVlWp0JmFImimPzjJ7K+CxZfI1RiwJULU2hBn+d4+4XGU2mFyvkdWoR/gP+cujs2JCFYGt7VNzdnuFqsENv6Q6hDTXNvTMPp9aQWfXhnmpjobUdZBjbkUGTUsjv6sDGHzAwoAekT/oEFWlIJGlCo68xqPYjaUa5Njpj7raXcv7iW+fnYknFQPYYPZDV53uBSBlH0pFdqhkSXFLueeEUGWxJ3xeQ8gbV/Dm+gkjkV6Nh8zKslRsfO9QIDAQAB-----END PUBLIC KEY-----


springdoc:
  swagger-ui:
    filter: true
server:
  port: 8081
  file:
    basePath: /Users/bibek/Desktop/workspace/photo/
authorize:
  url: http://localhost:8765
  password: sso_laconic
  file: /Users/bibek/Downloads/sso.p12

