spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: jobonic
    password: jobonic
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  swagger-ui:
    filter: true
server:
  port: 8081
  file:
    basePath: ${DOCUMENT_BASE_PATH}

