spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: jobonic
    password: jobonic
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
springdoc:
  swagger-ui:
    filter: true
server:
  port: 8081
