package com.laconic.fastworkapi.enums;

public enum Status {
    ENQUIRING,
    APPLICANT,
    WAITING_FOR_SUBMISSION,
    TO_APPROVE,
    TO_REVIEW,
    CANCELLED,
    COMPLETED,
    ALL,
    APPLIED,
    TO_SUBMIT,
    WAITING_FOR_REVIEW,
    WAITING_FOR_FINAL_REVIEW,
    WAITING_FOR_FINAL_SUBMISSION,
    REJECTED
}